[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@aws-sdk/client-s3"]

[dev]
  framework = "#static"
  targetPort = 3999
  publish = "public"
  autoLaunch = true
