[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@aws-sdk/client-s3"]

[dev]
  framework = "#static"
  targetPort = 3999
  publish = "public"
  autoLaunch = true

# Exclude upload script from secrets scanning (contains config values, not secrets)
[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "upload-photo-to-s3.sh"
